### ISSUE TITLE
Infra: Service migration to Ubuntu 24.04 warrants upgrading to Python3

### ISSUE THREAD

**Issue by JacobCoffee** [python/planet#568]
## What

Hi, I work for the PSF and am currently in the process of upgrading hosts from various OS levels to the latest Ubuntu LTS (24.04 - which comes pre-packaged with Python3.12.3)

In working with the backend and readying the VM, I realized that the app code demands python2.

Can someone assist in upgrading this? I am available to help.

```[tasklist]
### Tasks
- [ ] Shebangs updated `python` -> `python3`
- [ ] `config/sort-ini.py`
- [ ] `code/*.py` files
```

Thanks :)

**Comment by ewdurbin** [comment]
ref #301
